[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
  { access = "read-write", path = "./json" },
  { access = "read-write", path = "./test/json" },
]
ffi = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
